# Generated by Django 6.0.5 on 2026-06-17 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rms', '0003_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('C', 'Cash'), ('K', 'Khalti'), ('E', 'Esewa'), ('F', 'Fonepay')], max_length=1)),
                ('pidx', models.CharField(max_length=22, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(default='Pending', max_length=15)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='rms.order')),
            ],
        ),
    ]
