# Generated by Django 6.0.5 on 2026-06-10 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="item",
                to="rms.food",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="item",
                to="rms.order",
            ),
        ),
    ]
