# Generated by Django 6.0.5 on 2026-06-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0002_alter_orderitem_food_alter_orderitem_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
