# Generated by Django 6.0.5 on 2026-06-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(default=9800000000, max_length=15),
            preserve_default=False,
        ),
    ]
