# Generated by Django 6.0.5 on 2026-06-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
